version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      MONGO_INITDB_DATABASE: testDb
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  user-service:
    build: .
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      env_mongodb_database: testDb
      env_mongodb_username: admin
      env_mongodb_password: admin
      env_mongodb_port: 27017
      env_mongodb_hosts: mongodb